GraphScope/portal

packages/studio-components/src/Utils/index.tsx, packages/studio-importor/package.json, packages/studio-importor/src/app/button-controller/export-image.tsx, packages/studio-importor/src/app/elements/arrow-marker/index.tsx, packages/studio-importor/src/app/elements/forceLayout.tsx, packages/studio-importor/src/app/elements/index.ts, packages/studio-importor/src/app/elements/node-types/graph-node.tsx, packages/studio-importor/src/app/graph-canvas/useInteractive.ts, packages/studio-importor/src/app/index.tsx, packages/studio-importor/src/app/properties-editor/index.tsx, packages/studio-importor/src/app/properties-editor/properties-schema/index.tsx, packages/studio-importor/src/app/properties-editor/properties-schema/validate-info.tsx, packages/studio-importor/src/app/properties-editor/scroll-container.tsx
=> feat: Resolve sidebar scrolling positioning issue, add image download in modeling page

packages/studio-components/src/SplitSection/index.tsx, packages/studio-website/src/components/select-cards/index.tsx, packages/studio-website/src/locales/en-US.ts, packages/studio-website/src/locales/zh-CN.ts, packages/studio-website/src/pages/extension/create-plugins.tsx, packages/studio-website/src/pages/extension/left-side.tsx, packages/studio-website/src/pages/extension/plugins.tsx, packages/studio-website/src/pages/extension/right-side.tsx, packages/studio-website/src/pages/extension/service.tsx, packages/studio-website/src/pages/extension/upload-files.tsx
=> feat: update extension

packages/studio-importor/src/app/utils/importing.tsx, packages/studio-query/src/app/content/index.tsx, packages/studio-query/src/app/content/welcome.tsx, packages/studio-query/src/app/context.tsx, packages/studio-query/src/app/index.tsx, packages/studio-query/src/app/sidebar/statement-list/index.tsx
=> feat：add a welcome message for the query page

packages/studio-query/src/app/content/header.tsx, packages/studio-query/src/app/content/index.tsx, packages/studio-query/src/app/context.tsx
=> feat: query content area scrolling

packages/studio-draw-pattern/.fatherrc.ts, packages/studio-draw-pattern/.gitignore, packages/studio-draw-pattern/README.md, packages/studio-draw-pattern/package.json, packages/studio-draw-pattern/src/components/DrawPattern.tsx, packages/studio-draw-pattern/src/hooks/Cypher/useDecodeCypher.ts, packages/studio-draw-pattern/src/hooks/Cypher/useEncodeCypher.ts, packages/studio-draw-pattern/src/index.ts, packages/studio-draw-pattern/src/stores/edgesStore.ts, packages/studio-draw-pattern/src/stores/nodesStore.ts, packages/studio-draw-pattern/src/types/GPE.d.ts, packages/studio-draw-pattern/src/types/edge.d.ts, packages/studio-draw-pattern/src/types/node.d.ts, packages/studio-draw-pattern/src/types/property.d.ts, packages/studio-draw-pattern/src/types/variable.d.ts, packages/studio-draw-pattern/test/case.ts, packages/studio-draw-pattern/tsconfig.json
- make dir structure
- complete node & edge state code
- model.json GPE
=> feat: dir structure

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md, Dockerfile, README.md, README.zh-CN.md
- fixed: https://github.com/GraphScope/portal/issues/306
=> Refine dockerfile

packages/studio-query/src/app/sidebar/section.tsx
=> feat: the list of stored procedures is not fully shown

packages/studio-website/src/pages/modeling/save-modeling.tsx
=> feat: Interface is still pending, but the display is incorrect

examples/graph-apps/src/index.tsx, examples/graph-apps/src/online-visual-tool/index.tsx, package.json, packages/studio-components/package.json, packages/studio-components/src/PropertiesList/utils.ts, packages/studio-components/src/Utils/parseCSV.ts, packages/studio-components/src/Utils/parseJSON.ts, packages/studio-components/src/Utils/parseSQL.tsx, packages/studio-graph/src/components/LoadCSV/index.tsx
=> Chore: Add online-visual-tool app

packages/studio-website/src/components/locale-switch/index.tsx
=> feat: update setting LocaleSwitch

packages/studio-importor/src/locales/en-US.ts, packages/studio-importor/src/locales/zh-CN.ts, packages/studio-website/src/pages/importing/start-importing.tsx, packages/studio-website/src/pages/importing/start-load.tsx, packages/studio-website/src/pages/instance/lists/service.tsx, packages/studio-website/src/pages/utils.ts
=> feat: delte list tip

packages/studio-components/src/EmptyCanvas/index.tsx, packages/studio-components/src/Provider/useCustomToken.tsx, packages/studio-components/src/layout/index.tsx, packages/studio-importor/src/app/button-controller/right-button.tsx, packages/studio-importor/src/app/graph-canvas/index.tsx, packages/studio-importor/src/app/import-schema/index.tsx, packages/studio-website/src/components/section/index.tsx, packages/studio-website/src/layouts/index.tsx, packages/studio-website/src/pages/setting/index.tsx
=> feat: update-style

packages/studio-driver/src/cypher-driver.ts, packages/studio-driver/src/gremlin-driver.ts, packages/studio-graph/src/components/Prepare/utils.tsx, packages/studio-graph/src/hooks/utils.tsx
fixed: https://github.com/GraphScope/portal/issues/498
=> feat: Add verification of query results

packages/studio-components/src/Icons/Arrow.tsx, packages/studio-components/src/Icons/Punctuation.tsx, packages/studio-components/src/Icons/index.tsx, packages/studio-query/src/statement/result/RawTable/groot-table.tsx, packages/studio-query/src/statement/result/RawTable/interanctive-expand.tsx, packages/studio-query/src/statement/result/RawTable/interanctive-table.tsx, packages/studio-query/src/statement/result/RawTable/json-show.tsx, packages/studio-query/src/statement/result/RawTable/typing.ts, packages/studio-query/src/statement/result/table.tsx
=> feat: add rawtable

examples/graph-apps/src/online-visual-tool/index.tsx, packages/studio-components/src/layout/index.tsx, packages/studio-graph/src/components/CurvatureLinks/index.tsx, packages/studio-graph/src/components/Prepare/index.tsx, packages/studio-graph/src/components/index.tsx, packages/studio-importor/src/app/graph-canvas/index.tsx, packages/studio-importor/src/app/graph-canvas/useInteractive.ts, packages/studio-importor/src/app/index.tsx, packages/studio-website/src/pages/setting/primary-color/select-color.tsx, packages/use-zustand/src/index.tsx
- merge multiple edges by default
=> feat: Support for merging multiple edges 

examples/graph-apps/src/online-visual-tool/index.tsx, packages/studio-graph/package.json, packages/studio-graph/src/components/BasicInteraction/index.tsx, packages/studio-graph/src/components/DagreMode/index.tsx, packages/studio-graph/src/components/LoadCSV/index.tsx, packages/studio-graph/src/components/PropertiesPanel/index.tsx, packages/studio-graph/src/components/index.tsx, packages/studio-graph/src/graph/custom-edge/index.tsx, packages/studio-graph/src/graph/types.ts, packages/studio-graph/src/graph/useGraph.ts, packages/studio-graph/src/hooks/useEdgeClick.ts, packages/use-zustand/src/index.tsx
- fixed: https://github.com/GraphScope/portal/issues/550
=> feat: Support click events on edges and display properties details.

packages/studio-driver/src/cypher-driver.ts
- reference: https://github.com/neo4j/neo4j-javascript-driver/issues/1147
=> chore: disable encrypted

package.json, packages/studio-website/package.json, packages/studio-website/src/app.tsx, packages/studio-website/src/index.tsx, packages/studio-website/src/pages/index.tsx
=> release: v0.1.8

examples/graphy/src/index.tsx, examples/graphy/src/kuzu-driver/index.tsx, packages/studio-explore/package.json, packages/studio-explore/src/app.tsx, packages/studio-explore/src/components/Connection/import-into-kuzu/index.tsx, packages/studio-explore/src/components/Connection/import-into-kuzu/transform.tsx, packages/studio-explore/src/components/Connection/index.tsx, packages/studio-explore/src/services/graphscope.tsx, packages/studio-explore/src/services/index.tsx, packages/studio-explore/src/services/kuzu-wasm.tsx, packages/studio-explore/src/services/utils.tsx, packages/studio-graph/src/components/Placeholder/index.tsx, packages/studio-graph/src/components/index.tsx, packages/studio-graph/src/hooks/typing.tsx, packages/studio-importor/src/app/import-schema/import-from-csv/index.tsx, packages/studio-importor/src/app/import-schema/import-from-csv/web-worker.tsx, packages/studio-importor/src/index.tsx, packages/studio-website/package.json, packages/studio-website/vite.config.ts, pnpm-lock.yaml
=> feat: Support  kuzu wasm

python/graphy/apps/demo_app.py, python/graphy/models/__init__.py, python/graphy/models/embedding_model.py, python/graphy/paper_scrapper.py, python/graphy/requirements.txt, python/graphy/tests/workflow/inspector_navigator_test.py, python/graphy/tests/workflow/paper_inspector_test.py, python/graphy/utils/text_clustering.py
As titled, and remove the dependency of torchtext.
=> fix: remove GloveEmbedding implementation in clustering

packages/studio-website/src/pages/job/circle-animation.tsx, packages/studio-website/src/pages/job/job-header.tsx, packages/studio-website/src/pages/job/job-list.tsx, packages/studio-website/src/pages/job/service.tsx, packages/studio-website/src/pages/job/useStore.tsx
=> feat: change job

packages/studio-website/src/pages/job/job-list.tsx, packages/studio-website/src/pages/job/useStore.tsx
=> feat: update time

python/graphy/apps/paper_reading/paper_navigate_edge.py, python/graphy/apps/paper_reading/paper_reading_nodes.py, python/graphy/config/workflow_navigator.json
=> fix(graphy): fix a bug of wrong parameter assignment in PaperNavigateEdge

.dumirc.ts, packages/studio-graph/docs/const.ts, packages/studio-graph/docs/index.zh-CN.md, packages/studio-graph/docs/online.zh-CN.md, packages/studio-graph/docs/performance-1.zh-CN.md, packages/studio-graph/docs/performance-2.zh-CN.md, packages/studio-graph/docs/performance-3.zh-CN.md, packages/studio-graph/docs/provider.zh-CN.md, packages/studio-graph/docs/quick.zh-CN.md, packages/studio-graph/docs/render.zh-CN.md, packages/studio-graph/src/components/LoadCSV/index.tsx, packages/studio-graph/src/graph/custom-node/index.tsx, packages/studio-graph/src/graph/handleStyle.tsx, packages/studio-graph/src/graph/useGraph.ts, packages/studio-graph/tsconfig.json
=> feat: Update graph docs

python/graphy/apps/paper_reading/survey_paper_reading.py, python/graphy/models/embedding_model.py, python/graphy/tests/nlp/extract_reference_test.py, python/graphy/tests/nlp/get_paper_bib_test.py, python/graphy/tests/workflow/paper_inspector_test.py, python/graphy/utils/paper_expansion.py, python/graphy/utils/text_clustering.py
update Embedding Class
```
class MyEmbedding(EmbeddingFunction):
def __init__(self):
self.embed_model = embedding_functions.DefaultEmbeddingFunction()
def __call__(self, text_data: List[str]) -> Embeddings:
return self.embed_model.embed_with_retries(text_data)
@staticmethod
def get_name():
return "ONNXMiniLM_L6_V2"
```
implement `__call__()` to use different embedding functions
=> update default embedding

examples/graphy/CHANGELOG.md, examples/graphy/package.json, packages/studio-components/CHANGELOG.md, packages/studio-components/package.json, packages/studio-draw-pattern/CHANGELOG.md, packages/studio-draw-pattern/package.json, packages/studio-driver/CHANGELOG.md, packages/studio-driver/package.json, packages/studio-explore/CHANGELOG.md, packages/studio-explore/package.json, packages/studio-graph-editor/CHANGELOG.md, packages/studio-graph-editor/package.json, packages/studio-graph/CHANGELOG.md, packages/studio-graph/package.json, packages/studio-importor/CHANGELOG.md, packages/studio-importor/package.json, packages/studio-query/CHANGELOG.md, packages/studio-query/package.json, packages/studio-server/CHANGELOG.md, packages/studio-server/package.json, packages/studio-website/CHANGELOG.md, packages/studio-website/package.json, packages/use-zustand/CHANGELOG.md, packages/use-zustand/package.json
- https://github.com/GraphScope/portal/pull/623
- https://github.com/GraphScope/portal/pull/627
- https://github.com/GraphScope/portal/pull/628
- https://github.com/GraphScope/portal/pull/625
=> release: v0.1.9

examples/graphy/CHANGELOG.md, examples/graphy/package.json, packages/studio-components/CHANGELOG.md, packages/studio-components/package.json, packages/studio-draw-pattern/CHANGELOG.md, packages/studio-draw-pattern/package.json, packages/studio-driver/CHANGELOG.md, packages/studio-driver/package.json, packages/studio-explore/CHANGELOG.md, packages/studio-explore/package.json, packages/studio-graph-editor/CHANGELOG.md, packages/studio-graph-editor/package.json, packages/studio-graph/CHANGELOG.md, packages/studio-graph/package.json, packages/studio-importor/CHANGELOG.md, packages/studio-importor/package.json, packages/studio-query/CHANGELOG.md, packages/studio-query/package.json, packages/studio-server/CHANGELOG.md, packages/studio-server/package.json, packages/studio-website/CHANGELOG.md, packages/studio-website/package.json, packages/use-zustand/CHANGELOG.md, packages/use-zustand/package.json
- https://github.com/GraphScope/portal/pull/632
- https://github.com/GraphScope/portal/pull/633
- https://github.com/GraphScope/portal/pull/636
- https://github.com/GraphScope/portal/pull/637
- https://github.com/GraphScope/portal/pull/638
- fixed: https://github.com/GraphScope/portal/issues/630
- fixed: https://github.com/GraphScope/portal/issues/552
- fixed: https://github.com/GraphScope/portal/issues/553
=> release: v0.1.10

examples/graphy/CHANGELOG.md, examples/graphy/package.json, packages/studio-components/CHANGELOG.md, packages/studio-components/package.json, packages/studio-draw-pattern/CHANGELOG.md, packages/studio-draw-pattern/package.json, packages/studio-explore/CHANGELOG.md, packages/studio-explore/package.json, packages/studio-graph-editor/CHANGELOG.md, packages/studio-graph-editor/package.json, packages/studio-graph/CHANGELOG.md, packages/studio-graph/package.json, packages/studio-importor/CHANGELOG.md, packages/studio-importor/package.json, packages/studio-query/CHANGELOG.md, packages/studio-query/package.json, packages/studio-website/CHANGELOG.md, packages/studio-website/package.json
- https://github.com/GraphScope/portal/pull/640
=> release: v0.1.11

.dumirc.ts, examples/graphy/src/pages/dataset/cluster/graph.tsx, packages/studio-explore/src/app.tsx, packages/studio-explore/src/components/CypherQuery/index.tsx, packages/studio-explore/src/components/FloatTabs/index.tsx, packages/studio-explore/src/components/FloatTabs/useResizeWidth.tsx, packages/studio-explore/src/components/Next/Neighbors/TableView.tsx, packages/studio-explore/src/components/Searchbar/index.tsx, packages/studio-explore/src/components/TableView/AdjustColumns.tsx, packages/studio-explore/src/components/TableView/SaveSelected.tsx, packages/studio-explore/src/components/TableView/getTableData.tsx, packages/studio-explore/src/components/TableView/index.tsx, packages/studio-graph/src/components/ClearStatus/index.tsx, packages/studio-graph/src/components/LayoutSetting/Params.tsx, packages/studio-graph/src/components/LayoutSetting/index.tsx, packages/studio-graph/src/components/PropertiesPanel/PropertiesTable.tsx, packages/studio-graph/src/components/PropertiesPanel/PropertyInfo.tsx, packages/studio-graph/src/components/PropertiesPanel/index.tsx, packages/studio-graph/src/components/index.tsx, packages/studio-graph/src/graph/hooks/useApis.tsx, packages/studio-graph/src/graph/hooks/useDataAndLayout.tsx, packages/studio-query/src/app/sidebar/gpt-statements/index.tsx, packages/studio-query/src/components/query-graph/queryStatement.tsx, packages/studio-query/src/statement/result/table.tsx
- Optimize table rendering performance
- Support column filtering and row sorting
- Support saving selected nodes as new graph data
- Support for adjusting container width by dragging
- Support for the selection of multiple layout algorithms
- Support for fine-tuning layout parameters of force and force-dagre
bugfix：
- fixed：https://github.com/GraphScope/portal/issues/664
=> feat: Add TableView & Add LayoutSetting

packages/studio-explore/src/app.tsx, packages/studio-explore/src/components/FloatToolbar/index.tsx, packages/studio-explore/src/components/Searchbar/index.tsx, packages/studio-explore/src/components/index.tsx, packages/studio-graph/src/components/BasicInteraction/useNodeClick.ts, packages/studio-graph/src/components/Brush/index.tsx, packages/studio-graph/src/components/ClearCanvas/index.tsx, packages/studio-graph/src/components/ClearStatus/index.tsx, packages/studio-graph/src/components/LayoutSetting/Params.tsx, packages/studio-graph/src/components/LayoutSetting/index.tsx, packages/studio-graph/src/components/PropertiesPanel/PropertyInfo.tsx, packages/studio-graph/src/components/PropertiesPanel/index.tsx, packages/studio-graph/src/graph/hooks/useDataAndLayout.tsx
- fixed : https://github.com/GraphScope/portal/issues/593
=> Chore: fix some issues

python/graphy/extractor/paper_extractor.py, python/graphy/utils/arxiv_fetcher.py
=> Extract arxiv ids from references to get more cited papers

python/graphy/apps/paper_reading/paper_navigate_edge.py, python/graphy/apps/paper_reading/paper_reading_nodes.py, python/graphy/extractor/pdf_extractor.py, python/graphy/paper_scrapper.py, python/graphy/utils/arxiv_fetcher.py, python/graphy/workflow/__init__.py, python/graphy/workflow/multiproc_executor.py, python/graphy/workflow/ray_executor.py
Use more liteweight multiprocessor instead of ray for default paperscrapper on one machine
=> feat(graphy): Implement `multiprocessor` paper scrapper

python/graphy/apps/demo_app.py, python/graphy/apps/paper_reading/__init__.py, python/graphy/apps/paper_reading/paper_reading_nodes.py, python/graphy/apps/text_generator.py, python/graphy/extractor/paper_extractor.py, python/graphy/graph/nodes/__init__.py, python/graphy/graph/nodes/base_node.py, python/graphy/graph/nodes/chain_node.py, python/graphy/graph/nodes/dag_node.py, python/graphy/tests/common/build_graph_test.py, python/graphy/tests/common/fix_json_test.py, python/graphy/tests/workflow/paper_inspector_test.py
=> refactor(graphy): Provide a common DAGInspector abstract

packages/studio-explore/src/components/Copilot/index.tsx, packages/studio-explore/src/components/Copilot/query.tsx, packages/studio-explore/src/components/Report/Intention.tsx, packages/studio-explore/src/components/Report/Think/index.tsx, packages/studio-explore/src/components/Report/Write.tsx, packages/studio-explore/src/components/Report/index.tsx
- fixed: https://github.com/GraphScope/portal/issues/692
- fixed: https://github.com/GraphScope/portal/issues/691
=> Feat: Support streaming output for report generation

python/graphy/graph/nodes/pdf_extract_node.py, python/graphy/utils/data_extractor.py
When summary/abstract cannot be fetched from arxiv, simply add it from extracted data.
=> feat(graphy): add extracted summary when cannot fetched

.github/workflows/deploy-portal-docs.yml, .github/workflows/npm-publish.yml, .github/workflows/prepare-publish.yml, package.json, packages/studio-driver/src/queryGraph.tsx, packages/studio-explore/src/app.tsx, packages/studio-explore/src/components/ChartView/BarChart.tsx, packages/studio-explore/src/components/FloatContainer/index.tsx, packages/studio-explore/src/components/FloatTabs/index.tsx, packages/studio-explore/src/components/Next/Neighbors/index.tsx, packages/studio-explore/src/components/Searchbar/PropertyChart.tsx, packages/studio-explore/src/components/Searchbar/PropertyChartSetting.tsx, packages/studio-explore/src/components/Setting/index.tsx, packages/studio-explore/src/components/Statistics/Properties/ChartView.tsx, packages/studio-explore/src/components/TableView/index.tsx, packages/studio-explore/src/services/cypher/queryPropertyStatics.tsx, packages/studio-graph/src/components/BasicInteraction/useEdgeClick.ts, packages/studio-graph/src/components/BasicInteraction/useNodeClick.ts, packages/studio-graph/src/components/PropertiesPanel/PropertyInfo.tsx, packages/studio-graph/src/components/ZoomStatus/index.tsx, packages/studio-graph/src/graph/custom-icons/index.tsx, packages/studio-graph/src/graph/hooks/useApis.tsx, packages/studio-graph/src/graph/hooks/useEdgeStyle.tsx, packages/studio-query/src/components/query-graph/index.tsx, pnpm-lock.yaml
- Add Statistical property fields, considering query performance, the default value is `[]`. fixed:https://github.com/GraphScope/portal/issues/712
- Support multiple selections on charts, fixed: https://github.com/GraphScope/portal/issues/711
- Set global id , fixed: https://github.com/GraphScope/portal/issues/709
=> feat: Update exploration

packages/studio-query/src/app/sidebar/recommended-statements/index.tsx
=> fix: #647 where attribute keys display incorrectly

packages/studio-components/src/Utils/index.md, packages/studio-explore/src/components/Next/Neighbors/index.tsx
=> Add documents for utils

packages/studio-driver/src/cypher-driver.ts
- fixed: https://github.com/GraphScope/portal/issues/720
- fixed: https://github.com/GraphScope/portal/issues/721
=> feat: Fix cases where the query result is a path.

packages/studio-website/src/pages/modeling/save-modeling.tsx
After saving the model, retrieve all legends again
=> fix: graphSelect bug

docs/interactive/components/Home/index.tsx, examples/mcp-portal/package.json, examples/mcp-portal/src/helpers.ts, examples/mcp-portal/src/index.ts, examples/mcp-portal/src/resource/index.ts, examples/mcp-portal/src/sse.ts, examples/mcp-portal/src/tools/index.ts, examples/mcp-portal/tsconfig.json, pnpm-lock.yaml
=> feat: Add a mcp demo for the portal.

packages/studio-importor/src/app/graph-canvas/useInteractive.ts
Fix the issue of the homepage legend not being centered
=> Fix the issue of the homepage legend not being centered

packages/studio-components/src/EmptyCanvas/index.md, packages/studio-components/src/ImportFiles/index.tsx, packages/studio-components/src/ImportFiles/mapping-header.tsx, packages/studio-components/src/ImportFiles/mapping.tsx, packages/studio-components/src/ImportFiles/update-file.tsx, packages/studio-components/src/Importor/index.zh-CN.md, packages/studio-components/src/SideTabs/index.md, packages/studio-importor/src/app/import-schema/import-from-csv/index.tsx
Add callback functions and transition states for all file uploads completed
=> Fix upfile graph model

packages/studio-components/src/Provider/getThemeConfig.tsx, packages/studio-website/src/pages/instance/lists/empty.tsx, packages/studio-website/src/pages/instance/lists/server-not-available.tsx
=> fix: Modify spacing variable

packages/studio-graph-editor/src/canvas/index.tsx, packages/studio-graph-editor/src/canvas/reactflowStyle.ts, packages/studio-graph-editor/src/reactflow-css.d.ts
=> fix: Modify style import

docs/interactive/CHANGELOG.md, docs/interactive/package.json, examples/graphy/CHANGELOG.md, examples/graphy/package.json, packages/studio-components/CHANGELOG.md, packages/studio-components/package.json, packages/studio-draw-pattern/CHANGELOG.md, packages/studio-draw-pattern/package.json, packages/studio-driver/CHANGELOG.md, packages/studio-driver/package.json, packages/studio-explore/CHANGELOG.md, packages/studio-explore/package.json, packages/studio-graph-editor/CHANGELOG.md, packages/studio-graph-editor/package.json, packages/studio-graph/CHANGELOG.md, packages/studio-graph/package.json, packages/studio-importor/CHANGELOG.md, packages/studio-importor/package.json, packages/studio-importor/src/app/properties-editor/properties-schema/validate-info.tsx, packages/studio-query/CHANGELOG.md, packages/studio-query/package.json, packages/studio-server/CHANGELOG.md, packages/studio-server/package.json, packages/studio-website/CHANGELOG.md, packages/studio-website/package.json, packages/studio-website/src/pages/importing/index.tsx, packages/studio-website/src/pages/importing/services.tsx, packages/studio-website/src/pages/modeling/index.tsx, packages/use-zustand/CHANGELOG.md, packages/use-zustand/package.json
=> fix: Modify variable runtime to define environment variables

packages/neug-query/package.json
update neug-query build script
=> fix: update neug-query build
